services:
  db:
    image: postgres:14-alpine
    container_name: postgres_db_dev
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT:-5432}:5432"
    restart: unless-stopped
    # Add a healthcheck to ensure the database is ready
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
  web:
    container_name: fiap-web-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      APP_PORT: ${APP_PORT}
      NODE_ENV: ${NODE_ENV:-development}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-24h}
      LOG_LEVEL: ${LOG_LEVEL:-info}
      NEW_RELIC_ENABLED: ${NEW_RELIC_ENABLED:-false}
      NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY:-}
      NEW_RELIC_APP_NAME: ${NEW_RELIC_APP_NAME:-fiap-web-dev}
      NEW_RELIC_LOG_LEVEL: ${NEW_RELIC_LOG_LEVEL:-info}
      RABBITMQ_URL: amqp://${RABBITMQ_USER:-guest}:${RABBITMQ_PASSWORD:-guest}@rabbitmq:5672
      RABBITMQ_EXCHANGE: ${RABBITMQ_EXCHANGE:-payment-events}
      RABBITMQ_QUEUE: ${RABBITMQ_QUEUE:-os-service.payment-events}
    ports:
      - "3000:${APP_PORT:-3000}"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - default
      - fiap-net

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: fiap-rabbitmq-dev
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-guest}
    ports:
      - "${RABBITMQ_PORT:-5672}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT:-15672}:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - default
      - fiap-net

networks:
  fiap-net:
    external: true
