FROM node:22-alpine

WORKDIR /app
COPY package*.json ./
RUN npm ci --ignore-scripts
COPY tsconfig*.json ./
COPY src ./src
COPY .sequelizerc ./
ENV NODE_ENV=development
ENV APP_PORT=3000
EXPOSE 3000
CMD ["/bin/sh", "-c", "npm run migrate && npm run seed && npm run dev"]