sonar.projectKey=zmathmatos_fiap-soat-os-service
sonar.organization=zmathmatos
sonar.projectName=fiap-soat-os-service

sonar.sources=./src
sonar.tests=./tests

sonar.javascript.lcov.reportPaths=./coverage/lcov.info
sonar.coverage.exclusions=src/infrastructure/database/**/*, src/routers/**/*, **/*.test.ts
