apiVersion: v1
kind: Service
metadata:
  name: os-service
  labels:
    app: os-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
spec:
  type: LoadBalancer
  selector:
    app: os-service
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
